version: "3.7"

services:
  geth-authority:
    hostname: geth-authority
    env_file:
      - .env
    image: geth-authority:2.0
    build:
      context: .
      args:
        - PATH_BOOT_KEY=${PATH_BOOT_KEY}
    command:
      --nodekey /root/.ethereum/dchain/${PATH_BOOT_KEY}
      --datadir root/.ethereum/dchain
      --bootnodes ${BOOTNODE_ENODE}
      --syncmode "full"
      --gcmode archive
      --networkid=${NETWORK_ID}
      --discovery.port 30305
      --port 30305
      --http
      --http.addr="0.0.0.0"
      --http.api="eth,web3,net,admin"
      --http.vhosts "0.0.0.0"
      --http.port 8545
      --http.corsdomain="http://localhost"
      --signer ${CLEF}
      --miner.etherbase=${PUBLIC_KEY}
      --mine
      --ethstats ${ETH_STATS}
      --maxpeers 100
      --cache 1024
    ports:
      - "30303:30303"
      - "30305:30305"
    volumes:
      - ${PATH_DCHAIN}:/root/.ethereum/dchain
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    name: priv-eth-net
    external: true
